// AUTO-GENERATED from viz-list.ts by scripts/generate-featured.mjs — DO NOT EDIT BY HAND.
// Contains only the `favorite: true` entries so the homepage can render them without
// bundling the full catalog. Regenerate with `npm run generate:featured`.
import type { VizItem } from "./viz-list-types";

export const featuredVizList: VizItem[] = [
    {
        id: 1,
        title: "Here’s When We Expect Omicron to Peak",
        date: new Date(2022, 0),
        author: "The New York Times",
        url: "https://www.nytimes.com/2022/01/06/opinion/omicron-covid-us.html",
        img: { full: "omicron-NYT.png", zoom: "omicron-NYT-zoom.png", chartId: ["stream"] },
        contextDescription: "We're in early 2022, the Omicron variant importance is raising across the globe and the New york times decides to represent the Covid pandemic evolution of the last 2 years.",
        chartDescription: "The New York Times <a href='https://twitter.com/FreedZach/status/1479132573578240001'>literally broke the internet</a> with this circular streamgraph. The dataviz community is divided, trying to understand if this unconventional figure is pure genius or trash, since it does not respect most of the comon rules.<br/><br/>Hint: when so many people talk about a chart, there is probably something good about it!",
        luminosity: ["light"],
        interactive: false,
        labels: ["annotation", "direct labeling", "minimalist", "radial"],
        favorite: true
    },
    {
        id: 2,
        title: "Covid 19 Dashboard - India — map",
        date: new Date(2021, 10),
        author: "Group of dedicated volunteers",
        url: "https://www.covid19india.org",
        img: { full: "covid19India.png", zoom: "covid19India-zoom.png", chartId: ["map", "bubbleMap"] },
        contextDescription: "The covid crisis is a world wide pandemic and India is certainly not spared. Some volunteer decided to create a dashboard to help Indian politics to take information driven decisions.",
        chartDescription: "The dashboard's overview: an interactive bubble map of India on a dark base map, where each circle marks a district sized by its case count. A search box lets you jump to any state or district. Slick dark-mode design with smooth transitions.",
        tools: [{ name: "react", link: "https://github.com/covid19india/covid19india-react" }, { name: "d3.js", link: "https://github.com/covid19india/covid19india-react" }],
        luminosity: ["dark"],
        interactive: true,
        labels: ["interactive controls", "animation", "tooltip"],
        favorite: true
    },
    {
        id: 40,
        title: "Climate stripes",
        date: new Date(2018, 4),
        author: "Ed Hawkins",
        url: "https://showyourstripes.info/s/globe",
        img: { full: "climate-stripes.png", zoom: "climate-stripes-zoom.png", chartId: ["heatmap"] },
        contextDescription: "Warming stripes reflect a minimalist style, conceived to use colour alone to avoid technical distractions and intuitively convey global warming trends to non-scientists.",
        chartDescription: "Warming stripes (sometimes referred to as climate stripes, climate timelines or stripe graphics are data visualization graphics that use a series of coloured stripes chronologically ordered to visually portray long-term temperature trends.",
        tools: undefined,
        luminosity: ["light", "dark"],
        interactive: false,
        labels: ["minimalist", "color palette", "gradient"],
        favorite: true
    },
    {
        id: 59,
        title: "The Spread of QAnon — streamchart",
        date: new Date(2022, 2),
        author: "Cédric Scherer",
        url: "https://cemas.io/en/publikationen/q-vadis-the-spread-of-qanon-in-the-german-speaking-world/CeMAS_Q_Vadis_The_Spread_of_QAnon_in_the_German-Speaking_World.pdf",
        img: { full: "spread-of-qanon-1.png", zoom: "spread-of-qanon-zoom-1.png", chartId: ["stream"] },
        contextDescription: "The central piece of a study on the spread of QAnon in the german-speaking world. It shows the amount of QAnon related messages exchanged on Telegram.",
        chartDescription: "A large streamchart tracing the volume of QAnon-related Telegram messages over time, with an orange flow at top and stacked brown bands below. Numerous annotations point to key moments such as the spike around the Storming of the Capitol.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["annotation", "color palette", "storytelling"],
        favorite: true
    },
    {
        id: 71,
        title: "Bussed out — flow diagram",
        date: new Date(2017, 11),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/bussed-out/",
        img: { full: "bussed-out-1.png", zoom: "bussed-out-zoom-1.png", chartId: ["density"] },
        contextDescription: "Each year, US cities give thousands of homeless people one-way bus tickets out of town. An 18-month nationwide investigation by the Guardian reveals, for the first time, what really happens at journey’s end.",
        chartDescription: "A flow diagram showing bus ticket recipients fanning out from a single origin city, with red strands rising to higher-income destinations (12%) and blue strands descending to lower-income ones (88%), paired with a vertical density curve on the right.",
        tools: [{ name: "d3.js", link: undefined }],
        luminosity: ["light"],
        interactive: true,
        labels: ["flow & arrows", "annotation", "direct labeling", "color palette"],
        favorite: true
    },
    {
        id: 81,
        title: "Bundling on map",
        date: new Date(2021, 6),
        author: "Holten et al.",
        url: "https://www.data-to-viz.com/graph/edge_bundling.html",
        img: { full: "map-bundling.png", zoom: "map-bundling-zoom.png", chartId: ["map", "edgeBundling", "connection"] },
        contextDescription: "This figure is part of a paper called 'Force-Directed Edge Bundling for Graph Visualization'. It represents the US airlines connections and studies a variety of bundling algorithms.",
        chartDescription: "You can read the complete research paper <a href='https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.212.7989&rep=rep1&type=pdf'>here</a>, that compares different values for the bundling. It shows very well how useful can be bundling.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["flow & arrows", "highlight", "minimalist"],
        favorite: true
    },
    {
        id: 95,
        title: "Visit Vincent",
        date: new Date(2022, 4),
        author: "Julia Borsi",
        url: "https://public.tableau.com/app/profile/j.lia.borsi5912/viz/VisitVincent/VisitVincent",
        img: { full: "visit-vincent.png", zoom: "visit-vincent-zoom.png", chartId: ["map", "sankey"] },
        contextDescription: "St Vincent and the Grenadines is a southern Caribbean island country. The country is made of 32 islands, only 9 of them are actually inhabited. It is a tropical paradise visited by many people.",
        chartDescription: "The project is a mix between a map of the country and a sankey diagram.",
        tools: [{ name: "tableau", link: "https://public.tableau.com/app/profile/j.lia.borsi5912/viz/VisitVincent/VisitVincent" }],
        luminosity: ["light"],
        interactive: false,
        labels: ["flow & arrows", "full-page layout", "typography", "color palette"],
        favorite: true
    },
    {
        id: 108,
        title: "How I've spent my time",
        date: new Date(2022, 1),
        author: "Alli Torban",
        url: "https://twitter.com/researchremora/status/1527361112022593538",
        img: { full: "how-i-have-spent-my-time.png", zoom: "how-i-have-spent-my-time-zoom.png", chartId: ["stream"] },
        contextDescription: "A visual representation on how Alli spent here time through her life, split by categories like caretaking, leisure, work and more. Inspired by <a href='https://www.carniklirs.com/project/spare-time-over-a-lifetime'>Carni Klirs</a> work.",
        chartDescription: "A great streamgraph, totally adapted at showing the evolution of each category through time in a flowing style. I really like the texture employed here, giving it a personal nature.",
        tools: [{ name: "rawGraphs", link: undefined }],
        luminosity: ["light"],
        interactive: false,
        labels: ["texture", "direct labeling", "color palette"],
        favorite: true
    },
    {
        id: 110,
        title: "World Resources Report — waterfall chart",
        date: new Date(2022, 1),
        author: "Carni Klirs",
        url: "https://www.carniklirs.com/project/spare-time-over-a-lifetime",
        img: { full: "world-resources-report-1.png", zoom: "world-resources-report-1-zoom.png", chartId: ["barplot"] },
        contextDescription: "The <a href='https://research.wri.org/wrr-food'>World Resource Institute</a> (WRI) studies how to create a sustainable food future. It published a final report giving solutions to ensure the world can feed 10 billion people by 2050 in a sustainable way. It contains many great vizs.",
        chartDescription: "A waterfall (bridge) chart showing how a series of agricultural mitigation measures step down GHG emissions from a 2050 baseline of 15 Gt to the target. Each step is annotated with the specific intervention and grouped into shaded vertical bands by category.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["annotation", "color palette", "direct labeling"],
        favorite: true
    },
    {
        id: 116,
        title: "Bruxelles Malade — choropleth map",
        date: new Date(2022, 5),
        author: "Catherine Joie et al.",
        url: "https://bxl-malade.medor.coop",
        img: { full: "bruxelle-malade-1.png", zoom: "bruxelle-malade-zoom-1.png", chartId: ["map", "choropleth"] },
        contextDescription: "A scrollytelling article (in french) that talks about health in Bruxelles, the capital of Belgium. It highlights the discrepencies that exist between suburbs. A in-depth investigation definitely worth a read.",
        chartDescription: "A dark, detailed choropleth map of Brussels shading individual building footprints along a teal-to-orange diverging scale, revealing a sharp spatial divide between neighborhoods.",
        tools: undefined,
        luminosity: ["dark"],
        interactive: true,
        labels: ["color palette", "bivariate coloring", "minimalist"],
        favorite: true
    },
    {
        id: 125,
        title: "Tech startup evolution",
        date: new Date(2018, 6),
        author: "Bureau Oberhaeuser",
        url: "https://www.behance.net/gallery/59504801/Tech-Startup-Evolution-Calendar-2018",
        img: { full: "tech-startup-evolution.png", zoom: "tech-startup-evolution-zoom.png", chartId: ["network"] },
        contextDescription: "A circular calendar showing the evolution of the most significant tech companies of our time. Show features like market value, purchase price, number of employees and more.",
        chartDescription: "This is a circular lollipop chart. It displays a big amount of information for each company and I like the color choices that makes it look futuristic.",
        tools: undefined,
        luminosity: ["dark"],
        interactive: false,
        labels: ["radial", "color palette", "legend"],
        favorite: true
    },
    {
        id: 128,
        title: "A tree for U.S. immigration",
        date: new Date(2018, 6),
        author: "Pedro Cruz et al.",
        url: "https://web.northeastern.edu/naturalizing-immigration-dataviz/",
        img: { full: "tree-us-immigration.png", zoom: "tree-us-immigration-zoom.png", chartId: ["circularBarplot"] },
        contextDescription: "A circular graph mimicking the shape of a tree. It represents immigration in the U.S: each dot represents 100 immigrants. Distance to the center represents the date. Angle represents the migrant origin.",
        chartDescription: "This chart is unique, it does not belong to any chart type I know. And that's probably what makes it so famous and inspiring. Awesome metaphor, probably closer to data art than dataviz though.",
        tools: undefined,
        luminosity: ["dark"],
        interactive: false,
        labels: ["radial", "color palette"],
        favorite: true
    },
    {
        id: 129,
        title: "Remixing Rosling",
        date: new Date(2018, 6),
        author: "Moritz Stefaner",
        url: "https://truth-and-beauty.net/projects/remixing-rosling",
        img: { full: "remixing-rosling.png", zoom: "remixing-rosling-zoom.png", chartId: ["connectedScatter"] },
        contextDescription: "This chart is a remix of Hans Rosling's famous gapminder <a href='https://www.gapminder.org/tools/#$chart-type=bubbles&url=v1'>bubble chart</a>. It shows the evolution of life expectancy and fertility rate for a few countries.",
        chartDescription: "This is a very unique connected scatterplot. Bubble size is mapped to the year, which ease the understanding of the evolution and making the flow very smooth. It truly allows to 'feel' the evolution of each country!.",
        tools: [{ name: "tableau", link: "https://public.tableau.com/app/profile/jeffrey.shaffer/viz/RemixingRoslinginTableau/RemixingRosling" }],
        luminosity: ["light"],
        interactive: false,
        labels: ["highlight", "direct labeling", "annotation"],
        favorite: true
    },
    {
        id: 137,
        title: "Missing migrants",
        date: new Date(2022, 8),
        author: "Soha Elghany",
        url: "https://twitter.com/SohaElghany/status/1570725861384654849",
        img: { full: "missing-migrants.png", zoom: "missing-migrants-zoom.png", chartId: ["circularPacking"] },
        contextDescription: "A sad project tracking people who have died in the process of migration towards an internation destination. ",
        chartDescription: "A circular packing chart where each bubble is an incident that caused arms to migrants. Color related to origin location. Beautiful but sad.",
        tools: [{ name: "tableau", link: "https://public.tableau.com/app/profile/soha.elghany/viz/MissingMigrantsprintpt_1/Dashboard13" }],
        luminosity: ["light"],
        interactive: false,
        labels: ["color palette", "legend", "annotation"],
        favorite: true
    },
    {
        id: 142,
        title: "Flood Phenomena",
        date: new Date(2020, 8),
        author: "Tamás Varga",
        url: "https://public.tableau.com/app/profile/tam.s.varga/viz/FloodPhenomenainEurope/FloodPhenomenainEurope",
        img: { full: "flood-phenomena.png", zoom: "flood-phenomena-zoom.png", chartId: ["barplot", "stream"] },
        contextDescription: "A visual showing the number of flood phenomena in each of the European countries. A barchart on the left shows the most impacted countries. A stream chart on the right shows the evolution of the number of events.",
        chartDescription: "Data talks about floods, and the visual definitely goes along with it. The color palette and the organic shapes of the streamchart are going so well together. As often with nice visuals, the annotation tells the story.",
        tools: [{ name: "tableau", link: "https://public.tableau.com/app/profile/tam.s.varga/viz/FloodPhenomenainEurope/FloodPhenomenainEurope" }],
        luminosity: ["dark"],
        interactive: false,
        labels: ["color palette", "annotation", "storytelling"],
        favorite: true
    },
    {
        id: 147,
        title: "The slow loss — endangered birds dendrogram",
        date: new Date(2022, 10),
        author: "Michela Lazzaroni",
        url: "https://www.behance.net/gallery/151474693/The-Slow-Loss-La-Lettura-dataviz",
        img: { full: "the-slow-loss.png", zoom: "the-slow-loss-zoom.png", chartId: ["dendrogram"] },
        contextDescription: "This diptych shows the species of endangered birds and fishes in Italy, according to the IUCN's 'Red list'. For each animal, the following are indicated: common name, order, degree of danger, size and habitat.",
        chartDescription: "A circular dendrogram on a light background mapping endangered Italian birds, with warm-toned feather-like shapes radiating outward whose size encodes the animal. Small multiples of leaf/feather shapes run along the bottom as a legend.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["radial", "gradient", "color palette", "small multiples"],
        favorite: true
    },
    {
        id: 157,
        title: "The most important problem",
        date: new Date(2022, 9),
        author: "Gregor Aisch",
        url: "https://driven-by-data.net/2017/02/28/most-important-problem.html",
        img: { full: "most-important-problem.png", zoom: "most-important-problem-zoom.png", chartId: ["treemap"] },
        contextDescription: "Since the presidency of Franklin D. Roosevelt, the Gallup polling organization has asked Americans an open-ended question: “What do you think is the most important problem facing this country today?”",
        chartDescription: "A set of treemaps made for the New York Times",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["small multiples", "direct labeling", "color palette", "legend"],
        favorite: true
    },
    {
        id: 167,
        title: "Paid vacation days",
        date: new Date(2022, 12),
        author: "Samo Drole",
        url: "https://twitter.com/samodrole/status/1604341547817918464",
        img: { full: "Paid-vacation-days.jpeg", zoom: "Paid-vacation-days-zoom.jpeg", chartId: ["scatter"] },
        contextDescription: "This chart compares the number of paid vacation days in different countries around the world.",
        chartDescription: "A surprising way of showing a distribution: a scatterplot with jittering is used instead of a more classic histogram or density chart.",
        tools: undefined,
        luminosity: ["light"],
        interactive: true,
        labels: ["annotation", "direct labeling", "highlight"],
        favorite: true
    },
    {
        id: 214,
        title: "How Drug Overdose Deaths Have Plagued One Generation of Black Men for Decades",
        date: new Date(2024, 12),
        author: "The New York Times",
        url: "https://www.nytimes.com/2025/01/30/upshot/black-men-overdose-deaths.html?unlocked_article_code=1.m04.2sB5.vIYs6ISzHJnu",
        img: { full: "drug-overdose-black-men.png", zoom: "drug-overdose-black-men-zoom.png", chartId: ["heatmap"] },
        contextDescription: "The New York Times, in partnership with The Baltimore Banner, Big Local News, and nine other newsrooms, analyzed drug overdose deaths over the past decades. Through data, they found one common trend -- that drug overdose has been prevalent especially among Black men.",
        chartDescription: "Heatmap shows Covid deaths among Black men, showing a surge in drug deaths due to fentanyl among men born from 1951 to 1970.",
        tools: undefined,
        luminosity: ["light"],
        interactive: true,
        labels: ["annotation", "gradient", "color palette"],
        favorite: true
    },
    {
        id: 223,
        title: "From here to there: internal migration in Chile",
        date: new Date(2025, 9),
        author: "Dataista",
        url: "https://www.dataista.cl/interactivos/migracion-interna",
        img: { full: "chile-migration.png", zoom: "chile-migration-zoom.png", chartId: ["arc"] },
        contextDescription: "What are the movement patterns of Chileans within the country? Dataista uses the 2024 Population Census to find out.",
        chartDescription: "The interactive page allows you to explore each cicles, which represent each commune. The arcs show how people are moving from one commune to another. You can also read the full <a href='https://www.dataista.cl/articulos/2025/09/02/migracion-interna-censo-2024'>article</p>.",
        tools: undefined,
        luminosity: ["light"],
        interactive: true,
        labels: ["flow & arrows", "interactive controls", "color palette"],
        favorite: true
    },
    {
        id: 228,
        title: "Impeach this",
        date: new Date(2019, 10),
        author: "Tweet from Trump",
        url: "https://x.com/realDonaldTrump/status/1178989254309011456",
        img: { full: "impeach-this-trump.png", zoom: "impeach-this-trump-zoom.png", chartId: ["map", "choropleth"] },
        contextDescription: "A tweet by Donald Trump displaying a choropleth map of the 2016 election results. The map appears to suggest Trump’s victory but is misleading because it ignores the population size of each state.",
        chartDescription: "To be more specific, the colors misrepresent the population of each state, giving small and large states equal visual weight. A better alternative would be a bubble map, where each bubble represents a state and is sized according to its population. For a deeper discussion of this misleading map, see this <a href='https://prodigious-trailblazer-3628.kit.com/posts/foundational-dataviz-example'>newsletter</p>",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["annotation", "storytelling"],
        favorite: true
    },
    {
        id: 240,
        title: "A Classic Graphic Reveals Nature's Most Efficient Traveler",
        date: new Date(2025, 10),
        author: "Scientific American",
        url: "https://www.scientificamerican.com/article/a-human-on-a-bicycle-is-among-the-most-efficient-forms-of-travel-in-the/",
        img: { full: "scientific-american-efficient-traveler.png", zoom: "scientific-american-efficient-traveler-zoom.png", chartId: ["scatter", "correlogram"] },
        contextDescription: "Science American has updated its graphic, comparing lomotion in the animal kingdom.",
        chartDescription: "Chart shows relation between body weight and cost of transport, with each dot representing a specific animal.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["log scale", "color palette", "direct labeling"],
        favorite: true
    },
    {
        id: 244,
        title: "Every Writer of Chris Carter's TV Shows",
        date: new Date(2025, 10),
        author: "Ihar Yanouski",
        url: "https://yanouski.com/projects/xfiles-writers/",
        img: { full: "chris-carter-tvshow.png", zoom: "chris-carter-tvshow-zoom.png", chartId: ["bubble", "dendrogram", "chordDiagram", "network", "edgeBundling"] },
        contextDescription: "This project features screenwriters who took part in Chris Carter's TV shows, displaying the summary of contributions for each TV series.",
        chartDescription: "Cool infographic with interactive tools such as the sort options by first names, episode counts, and more. Definitely a lot of information to absorb, but the creator has nicely added a 'show legend' button on the bottom to explain how to read the chart.",
        tools: undefined,
        luminosity: ["dark"],
        interactive: true,
        labels: ["radial", "interactive controls", "color palette"],
        favorite: true
    },
    {
        id: 254,
        title: "Earth's Land Surface (A Voronoi World)",
        date: new Date(2020, 1),
        author: "Luca Urzì",
        url: "https://public.tableau.com/app/profile/luca7027/viz/EarthsLandSurfaceAVoronoiWorld/EarthsLandSurfaceAVoronoiWorld",
        img: { full: "land-surface-voronoi.png", zoom: "land-surface-voronoi-zoom.png", chartId: ["voronoi", "treemap"] },
        contextDescription: "Earth's land surface account for mere 27%, with the rest all water. This project shows visualization of land, comparing its mass among continents.",
        chartDescription: "Voronoi treemap shows proportions of land for each continent.",
        tools: undefined,
        luminosity: ["light"],
        interactive: true,
        labels: ["small multiples", "color palette", "direct labeling"],
        favorite: true
    },
    {
        id: 257,
        title: "Mapping the future of the AU-EU partnership — infrastructure map",
        date: new Date(2023, 1),
        author: "European Union Institute for Security Studies (EUISS)",
        url: "https://www.iss.europa.eu/sites/default/files/EUISSFiles/CP_180_screen_small.pdf",
        img: { full: "EU-AU-relation-map-1.png", zoom: "EU-AU-relation-map-1-zoom.png", chartId: ["map"] },
        contextDescription: "In partnership between the European Union (EU) and the African Union (AU), The European Union Institute for Security Studies published a data-heavy report on EU-AU relations.",
        chartDescription: "A detailed reference map of Africa plotting transport and settlement infrastructure: airports, ports, roads, railroads, urban areas and water bodies, with a categorical legend on a light background.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["legend", "icons & pictograms", "minimalist"],
        favorite: true
    },
    {
        id: 301,
        title: "More days with less Arctic sea ice",
        date: new Date(2024, 12),
        author: "Financial Times",
        url: "https://www.ft.com/content/63fbcf2b-9acc-4ccb-ac12-9f3b78e85b68?accessToken=zwAAAZvv7bK8kc9j-88rmsxMy9OsEp87eOhbaA.MEUCIEd6Dc46AyWNN4yyu3qFQ8gOoFELU-6CGeCmvf25GN5-AiEAuwOwEI66rDT0qk2bmYq3eufDfAFToinx6z3dO2WDSXA&segmentId=e95a9ae7-622c-6235-5f87-51e412b47e97&shareType=enterprise&shareId=27b72d04-71d2-4d72-95d4-22f8ec782d5f",
        img: { full: "less-arctic-sea-ice-financial-times.png", zoom: "less-arctic-sea-ice-financial-times-zoom.png", chartId: ["ridgeline"] },
        contextDescription: "New study shows that first ice-free day in the Arctic Ocean may come beofre 2030. Financial Times uses ridgeline plot to show the change in Arctic sea ice over the years.",
        chartDescription: "The distribution moving gradually towards the left shows the decrease in sea ice and what is to come ahead in the future.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["annotation", "gradient", "color palette", "direct labeling"],
        favorite: true
    },
    {
        id: 308,
        title: "French Rainfall",
        date: new Date(2024, 12),
        author: "Thomas Maguin",
        url: "https://www.linkedin.com/posts/thomas-maguin-bb1104189_kartotheque-gis-maeztaezo-activity-7241321164998946816-506m/?utm_source=share&utm_medium=member_desktop",
        img: { full: "france-rainfall-choropleth-map.png", zoom: "france-rainfall-choropleth-map-zoom.png", chartId: ["map", "choropleth"] },
        contextDescription: "A visual oveview of rainfall variations across France, highlighting the rainiest regions.",
        chartDescription: "",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["gradient", "annotation", "legend"],
        favorite: true
    },
    {
        id: 318,
        title: "Life expectancy vs. health expenditure",
        date: new Date(2020, 0),
        author: "Our World in Data",
        url: "https://ourworldindata.org/us-life-expectancy-low",
        img: { full: "life-expectancy-vs-health-spending.png", zoom: "life-expectancy-vs-health-spending-zoom.png", chartId: ["connectedScatter"] },
        contextDescription: "Americans spend far more on health than any other country, yet live shorter lives than people in other rich countries that spend much less. In the 1970s the US was not an outlier, but since then its health spending has exploded while life expectancy gains stalled — and have recently started to decline.",
        chartDescription: "A connected scatterplot where each line is a country, connecting yearly observations from 1970 to 2018: health spending per capita on the x-axis, life expectancy on the y-axis. Greying out every country except the USA (in red) instantly tells the story — the American line drifts far to the right without climbing much, breaking away from the tight cluster of other nations. A textbook example of how highlighting a single series turns a spaghetti of trajectories into a clear message.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false,
        labels: ["highlight", "annotation", "direct labeling"],
        favorite: true
    },
    {
        id: 320,
        title: "Voting shifts, 2004–2020",
        date: new Date(2021, 0),
        author: "The New York Times",
        url: "https://www.nytimes.com/2021/01/07/learning/whats-going-on-in-this-graph-voting-shifts.html",
        img: { full: "nyt-voting-shifts.png", zoom: "nyt-voting-shifts-zoom.png", chartId: ["line", "parallel"] },
        contextDescription: "Across five presidential elections from 2004 to 2020, how did each US state's partisan lean shift? This New York Times graphic places every state on a Democratic-to-Republican margin axis for each election year, tracing how solidly blue and red states moved — and which ones flirted with crossing the line.",
        chartDescription: "A bump-style line chart: each line is a state, threaded top-to-bottom through the five election years and positioned left-to-right by its voting margin, with a central 'Tie' line as the anchor. Blue and red encode the lean. The result reads almost like flowing currents, and the swings of swing states pop out immediately against the calm of the safe ones.",
        tools: [{ name: "d3.js" }],
        luminosity: ["light"],
        interactive: false,
        labels: ["annotation", "direct labeling", "comparison"],
        favorite: true
    }
];

// Total number of entries in the full list (for copy like "showcases N projects").
export const totalVizCount = 421;
