import { ChartId } from "./sectionDescription";

export const Tools = ["R" , "python" , "tableau" , "data wrapper" , "d3.js" , "react" , "excel" , "javascript"] as const;
export type Tool = typeof Tools[number];

export type Luminosity = "light" | "dark"

export type VizItem = {
    id: number;
    title: string;
    date: Date;
    author: string;
    url: string;
    img: {full: string, zoom: string, chartId: ChartId[]}[]; // zoom is on the wall. full is on the modal
    contextDescription: string;
    chartDescription: string;
    tools?: {name: Tool, link?: string}[]
    luminosity: Luminosity[];
    interactive: boolean
}

export const vizList: VizItem[] = [
    {
        id: 1,
        title: "Here’s When We Expect Omicron to Peak",
        date: new Date(2022, 0),
        author: "The New York Times",
        url: "https://www.nytimes.com/2022/01/06/opinion/omicron-covid-us.html",
        img: [{full: "omicron-NYT.png", zoom: "omicron-NYT-zoom.png", chartId: ["stream"]}],
        contextDescription: "We're in early 2022, the Omicron variant importance is raising across the globe and the New york times decides to represent the Covid pandemic evolutioin of the last 2 years.",
        chartDescription: "The New York Times <a href='https://twitter.com/FreedZach/status/1479132573578240001'>literally broke the internet</a> with this circular streamgraph. The dataviz community is divided, trying to understand if this unconventional figure is pure genius or trash, since it does not respect most of the comon rules.<br/><br/>Hint: when so many people talk about a chart, there is probably something good about it!",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 2,
        title: "Covid 19 Dashboard - India",
        date: new Date(2021, 10),
        author: "Group of dedicated volunteers",
        url: "https://www.covid19india.org",
        img: [
            {full: "covid19India.png", zoom: "covid19India-zoom.png", chartId: ["map", "bubbleMap"]},
            {full: "covid19India-bar.png", zoom: "covid19India-bar-zoom.png", chartId: ["barplot"]},
            {full: "covid19India-line.png", zoom: "covid19India-line-zoom.png", chartId: ["line"]}
        ],
        contextDescription: "The covid crisis is a world wide pandemic and India is certainly not spared. Some volunteer decided to create a dashboard to help Indian politics to take information driven decisions.",
        chartDescription: "A dashboard describing the spread of Covid 19 in India. Highly interactive with a pretty slick design. Dark mode support, many different types of viz with smooth transition between dataset.",
        tools: [{name: "react", link: "https://github.com/covid19india/covid19india-react"}, {name: "d3.js", link:"https://github.com/covid19india/covid19india-react"}],
        luminosity: ["light", "dark"],
        interactive: true
    },
    {
        id: 3,
        title: "Migration waves",
        date: new Date(1000, 0),
        author: "National Geographic",
        url: "https://www.nationalgeographic.com/magazine/graphics/graphic-shows-past-50-years-of-global-human-migration",
        img: [{full: "migration-waves.png", zoom: "migration-waves-zoom.png", chartId:  ["density", "ridgeline"]}],
        contextDescription: "The flow of people across borders has long shaped our world. Data from the past 50 years of international migration helped National Geographic understand why people make the choice to leave and where they go. Less than 10 percent of these migrants are forced to flee; most are seeking a better life and move only when they can afford to.",
        chartDescription: "The article describes the evolution of the immigration of many countries using smoothed area charts. The last figure looks pretty much like a ridgeline chart that is usually used to compare distributions, but smartly used here to compare evolutions.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 4,
        title: "Russia, Gas, and the Ukraine Conflict",
        date: new Date(2022, 2),
        author: "The New York Times",
        url: "https://www.nytimes.com/interactive/2022/02/15/business/energy-environment/russia-gas-europe-ukraine.html",
        img: [{full: "russia-gas-ukraine.png", zoom: "russia-gas-ukraine-zoom.png", chartId: ["sankey"]}],
        contextDescription: "Europe relies on Russia’s natural gas to help heat millions of homes, generate electricity and power factories. With Russian troops massed along Ukraine’s border, Europe’s heavy dependence on Russia is limiting its diplomatic options and threatening to throw its energy supplies into turmoil. This map describes what proportion of the gas supply is distributed to each European country.",
        chartDescription: "This viz is a choropleth map with a sankey diagram on top. The choropleth shows how much each country relies on Russian gaz. The sankey diagram (arrows) shows where the Russian gas is distributed.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 5,
        title: "Mario Kart world's records",
        date: new Date(2021, 4),
        author: "Cédric Scherer",
        url: "https://www.r-graph-gallery.com/web-lollipop-plot-with-r-mario-kart-64-world-records.html",
        img: [{full: "lollipop-plot-with-r-mario-kart-64-world-records.png", zoom: "lollipop-plot-with-r-mario-kart-64-world-records-zoom.png", chartId: ["lollipop"]}],
        contextDescription: "Mario Kart on Nintendo 64 is probably one of the most famouse game of all time (at least it is for me 😃). In this chart Cédric Scherer visualized the world records to understand what's the best character to play with.",
        chartDescription: "A lollipop chart grouped by character. It's interesting to notice that character names are not aligned vertically, but displayed next to each segment for better readability.",
        tools: [{name: "R", link: "https://www.r-graph-gallery.com/web-lollipop-plot-with-r-mario-kart-64-world-records.html"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 6,
        title: "Appearance of the Five Most Popular X-Men Characters",
        date: new Date(2020, 6),
        author: "Cédric Scherer",
        url: "https://www.r-graph-gallery.com/web-streamchart-with-ggstream.html",
        img: [{full: "streamchart-xmen.png", zoom: "streamchart-xmen-zoom.png", chartId: ["stream"]}],
        contextDescription: "A chart that studies the appearances of the most popular characters in Chris Claremont’s X-Men comics",
        chartDescription: "A set of aligned streamcharts with helpful annotations. Nice attention to details with striking color palette, great fonts and clear legend.",
        tools: [{name: "R", link: "https://www.r-graph-gallery.com/web-streamchart-with-ggstream.html"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 7,
        title: "Cracking your favorite password",
        date: new Date(2020, 0),
        author: "Cédric Scherer",
        url: "https://www.r-graph-gallery.com/web-circular-lollipop-plot-with-ggplot2.html",
        img: [{full: "web-circular-lollipop-plot-with-ggplot2.png", zoom: "web-circular-lollipop-plot-with-ggplot2-zoom.png", chartId: ["lollipop", "circularBarplot"]}],
        contextDescription: "Visualization of the time it takes to crack the 500 most common passwords by online guessing.",
        chartDescription: "A circular lollipop chart where each item is a password. Sorted by rank and colored by category. Annotation for the most extreme password, cool split by category at the bottom.",
        tools: [{name: "R", link: "https://www.r-graph-gallery.com/web-circular-lollipop-plot-with-ggplot2.html"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 8,
        title: "Infections caught in laboratories are surprisingly common",
        date: new Date(2021, 7),
        author: "the Economist",
        url: "https://www.economist.com/graphic-detail/2021/08/24/infections-caught-in-laboratories-are-surprisingly-common",
        img: [{full: "infection-from-lab.png", zoom: "infection-from-lab-zoom.png", chartId: ["barplot"]}],
        contextDescription: "In the middle of a worlwide pandemic, some people wonder if covid-19 escaped from a Chinese lab. The economist checked the probability of this by comparing with other diseases.",
        chartDescription: "A simple barplot with the well known Economics style signature. Note bars are displayed horizontally, each being labeled using a very readable manner.",
        tools: [{name: "python", link: "https://www.python-graph-gallery.com/web-horizontal-barplot-with-labels-the-economist"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 9,
        title: "Enrollments in historically black colleges",
        date: new Date(2022, 2),
        author: "Tobias Stalder",
        url: "https://www.r-graph-gallery.com/web-extended-dumbbell-plot-ggplot2.html",
        img: [{full: "HBCU_trends_gender.png", zoom: "HBCU_trends_gender-zoom.png", chartId: ["lollipop"]}],
        contextDescription: "A tidy tuesday challenge looking at how many males and females enrolled at historically black colleges and universities.",
        chartDescription: "A dumbbell plot made with ggplot2. On top of the nice layout and annotations, it also have additional grouped mean and standart deviation for each year.",
        tools: [{name: "R", link: "https://www.r-graph-gallery.com/web-extended-dumbbell-plot-ggplot2.html"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 10,
        title: "Covid dashboard",
        date: new Date(2021, 1),
        author: "Le Monde",
        url: "https://www.lemonde.fr/les-decodeurs/article/2020/05/05/coronavirus-age-mortalite-departements-pays-suivez-l-evolution-de-l-epidemie-en-cartes-et-graphiques_6038751_4355770.html",
        img: [{full: "covid-dash-lemonde-1.png", zoom: "covid-dash-lemonde-1.png", chartId: ["map"]}, {full: "covid-dash-lemonde-2.png", zoom: "covid-dash-lemonde-2-zoom.png", chartId: ["line"]}, {full: "covid-dash-lemonde-3.png", zoom: "covid-dash-lemonde-3-zoom.png", chartId: ["stream"]}, {full: "covid-dash-lemonde-4.png", zoom: "covid-dash-lemonde-4.png", chartId: ["line", "barplot"]}],
        contextDescription: "Covid is everywhere in the news and every newspaper is trying to summarize the situation in its country. Le Monde is one of the most famouse newspaper in France and does a pretty good job in its daily updated dashboard.",
        chartDescription: "Several viz are provided, going from mirror area charts to streamcharts, with different kinds of map and several tables. Worth a read if you speak 🇫🇷.",
        tools: [{name: "d3.js"}],
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 11,
        title: "Eigenfactor project",
        date: new Date(2018, 1),
        author: "Eigenfactor Project & Moritz Stefaner",
        url: "https://www.lemonde.fr/les-decodeurs/article/2020/05/05/coronavirus-age-mortalite-departements-pays-suivez-l-evolution-de-l-epidemie-en-cartes-et-graphiques_6038751_4355770.html",
        img: [{full: "scientific-pub-connection.png", zoom: "scientific-pub-connection-zoom.png", chartId: ["edgeBundling"]}],
        contextDescription: "A visualization of scientific publication citation network. More than 60M citations coming from more than 7k journals were considered. Goal was to look for patterns on how journals tend to cite each other.",
        chartDescription: "An interactive hierarchical edge bundling where each node is a scientific journal. A journal is linked with another through an edge if it cites it in one of its publication. Clicking on a specific journal highlights its connections.",
        tools: [{name: "d3.js"}],
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 12,
        title: "Inequality in Spain",
        date: new Date(2021, 11),
        author: "Dominic Royé",
        url: "https://dominicroye.github.io/en/project/population/",
        img: [{full: "map-inequality-spain.png", zoom: "map-inequality-spain-zoom.png", chartId: ["map", "choropleth"]}],
        contextDescription: "A visualization of Spain, looking a both inequality (using the Gini Index) and average rent prices.",
        chartDescription: "A dichotomous choropleth map with nice annotation, good looking color palette and a 2D color mapping.",
        tools: [{name: "R", link: "https://dominicroye.github.io/en/project/population/"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 13,
        title: "Troops Vs. Cost",
        date: new Date(2013, 10),
        author: "Jorge Camoes",
        url: "https://excelcharts.com/redraw-troops-vs-cost-time-magazine/",
        img: [{full: "Troops-vs-Costs.png", zoom: "Troops-vs-Costs-zoom.png", chartId: ["connectedScatter"]}],
        contextDescription: "The Time Magazine published a Dual-Y axis chart showing the evolution of both the army budget and the Number of troops between 1980 and 2012. Jorge Camoes decided to transform it with his own chart type.",
        chartDescription: "The result is a connected scatterplot. I personally prefer it since dual Y axis are notoriously <a href='https://www.data-to-viz.com/caveats.html'>broken</a>, but it's hard to know if people truely understand it when they're not used to it.",
        tools: [{name: "excel"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 14,
        title: "Vaccines and Infectious Diseases",
        date: new Date(2015, 1),
        author: "Dov Friedman & Tynan DeBold",
        url: "https://graphics.wsj.com/infectious-diseases-and-vaccines/",
        img: [{full: "vaccine-heatmap.png", zoom: "vaccine-heatmap-zoom.png", chartId: ["heatmap"]}],
        contextDescription: "Probably the most famous viz about vaccines. It represents the number of measle infected people measured over 70-some years and across all 50 states. It shows a clear trend of decline after vaccines were introduced.",
        chartDescription: "A clean heatmap that shows the number of cases per 100,000 people. Available for other diseases with similar result.",
        tools: [{name: "excel"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 15,
        title: "A Nation Divided",
        date: new Date(2014, 9),
        author: "Die Zeit",
        url: "https://www.zeit.de/feature/german-unification-a-nation-divided",
        img: [{full: "east-vs-west-germany.png", zoom: "east-vs-west-germany-zoom.png", chartId: ["hexbin"]}],
        contextDescription: "In the early euphoria following the fall of the Berlin Wall in 1989, Germany moved quickly to erase the scars of its Cold War division. But East Germany’s legacy remains visible in statistics. Die Zeit offers a set of maps showing the remaining discrepancies between the West and the East.",
        chartDescription: "A massive load of hexbin maps, showing various variables like the average income, the proportion of people called Ronny or the avera farm size. Smooth transition between variables and clean design.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 16,
        title: "Nobels, no degrees",
        date: new Date(2012, 10),
        author: "G. Lupi, S. Quadri, G. Rossi, D. Ciuffi, F. Fragapane, F. Majno",
        url: "https://www.behance.net/gallery/14159439/Nobel-no-degrees",
        img: [{full: "nobel-prices.png", zoom: "nobel-prices-zoom.png", chartId: ["line", "sankey", "barplot"]}],
        contextDescription: "This visualization explores the story of Nobel prizes through years.Visualized for each laureate are prize category, year the prize was awarded, and age of the recipient at the time, as well as principal academic affiliations and hometown.",
        chartDescription: "Each dot represents a Nobel laureate, and each recipient is positioned according to the year the prize was awarded (x axis) and his or her age at the time of the award (y axis).",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 17,
        title: "Shipmap.org",
        date: new Date(2012, 10),
        author: "Kiln",
        url: "https://www.shipmap.org",
        img: [{full: "shipmap.png", zoom: "shipmap-zoom.png", chartId: ["connection"]}, {full: "shipmap.png", zoom: "shipmap-2-zoom.png", chartId: ["connection"]}],
        contextDescription: "Shipmap.org is an interactive map of commercial shipping movements based on hundreds of millions of data points from throughout 2012. The project's aim is to highlight for a broad audience the extraordinary scale of modern commercial shipping, the routes these huge vessels take around the world, the geographic spread of different types of cargo boats, and the amount of carbon dioxide they produce.",
        chartDescription: "The unique base map shows ocean depth and major rivers, while the ships can be viewed as a high-resolution animation of movements over time (the 'ships' view) or as a plot showing all the positions at once (the 'routes' view), optionally colour-coded by ship type. A Talkie voiceover with music introduction sets the scene and provides an explanatory tour of the map.",
        tools: [{name: "javascript"}],
        luminosity: ["dark"],
        interactive: true
    },
    {
        id: 18,
        title: "Rhythm of Food",
        date: new Date(2016, 1),
        author: "M. Stefaner, Y. Vishnevsky, S. Rogers, A. Cairo et al.",
        url: "http://rhythm-of-food.net",
        img: [{full: "rhythm-food.png", zoom: "rhythm-food.png", chartId: ["heatmap"]}],
        contextDescription: "An interactive explorer based on the weekly Google Trends data for hundreds of dishes and ingredients, gathered over 15 years. It allows investigating the seasons and rhythm of food around the world",
        chartDescription: "The main viz of this project is a radial diagram. One viz per ingredient. The color of each square is for the year. The distance to center (radius) is for the number of google search.",
        tools: [{name: "javascript"}],
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 19,
        title: "The State of Javascript",
        date: new Date(2020, 1),
        author: "A. Wattenberger, S. Greif and R. Benitte",
        url: "https://2020.stateofjs.com/en-US/technologies/",
        img: [{full: "state-of-js.png", zoom: "state-of-js-zoom.png", chartId: ["connectedScatter"]}],
        contextDescription: "The State of Js is a survey that describes how Javascript (a programing language) evolved in the past few years. In the chart below they describe what libraries are trending, and which one are slowly disappearing. The whole webpage is awesome and you should definitely take a look.",
        chartDescription: "My favorite grouped connected scatterplot! Each line goes from 2016 to 2020. A higher point means a technology has been used by more people, and a point further to the right means more users want to learn it; or have used it and would use it again.",
        tools: [{name: "javascript", link: "https://github.com/StateOfJS/StateOfJS-2019/blob/master/src/core/charts/tools/ToolsArrowsChart/ToolsArrowsChart.js"}, {name: "d3.js", link: "https://github.com/StateOfJS/StateOfJS-2019/blob/master/src/core/charts/tools/ToolsArrowsChart/ToolsArrowsChart.js"}],
        luminosity: ["dark"],
        interactive: true
    },
    {
        id: 20,
        title: "Quantifying the evolution of individual scientific impact",
        date: new Date(2017, 0),
        author: "Kim Albrecht",
        url: "sciencepaths.kimalbrecht.com",
        img: [{full: "scientific-impact.png", zoom: "scientific-impact-zoom.png", chartId: ["line", "ridgeline"]}],
        contextDescription: "How does the impact of a scientist's work change over a scientific career? Does impact, arguably the most relevant performance measure, follow predictable patterns? Can we predict the timing of a scientist’s outstanding achievement? Kim checked the evolution of scientific author citation levels to answer those questions.<br/><br/>The result is called the <b>random impact rule</b>: the highest impact paper of a researcher can be anywhere in the sequence of papers!",
        chartDescription: "Each row is a scientist. From left to right, the first to the last paper of a scientist are arranged, ignoring their timing of publication. The line height shows the number of citation of the paper. The app has nice controls on top, including interactive histograms that I really like.",
        tools: [{name: "javascript"}, {name: "d3.js"}],
        luminosity: ["dark"],
        interactive: true
    },
    {
        id: 21,
        title: "Rappers, Sorted by Size of Vocabulary",
        date: new Date(2019, 0),
        author: "Matthew Daniels",
        url: "https://pudding.cool/projects/vocabulary/index.html",
        img: [{full: "rapper-lyrics.png", zoom: "rapper-lyrics-zoom.png", chartId: ["scatter", "bubble", "circularPacking"]}, {full: "rapper-lyrics-2.png", zoom: "rapper-lyrics-2-zoom.png", chartId: ["histogram"]}],
        contextDescription: "A projects that compares the number of unique words used by some of the most famous artists in hip hop using each artist’s first 35,000 lyrics. Jedi Mind Tricks used 6424 unique words, compared to DMX that counts 2936.",
        chartDescription: "A 1 dimension scatterplot where the X axis shows the number of unique words and each item is an artist, represented by a circle and an avatar. The Y position is random, just using <a href='https://www.data-to-viz.com/caveat/boxplot.html>jittering</a> to avoid overlap.",
        tools: [{name: "javascript"}],
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 22,
        title: "Shifting Parent Work Hours, Mom vs. Dad",
        date: new Date(2018, 0),
        author: "Nathan Yau",
        url: "https://flowingdata.com/2016/04/20/parent-work-hours/",
        img: [{full: "parent-work.png", zoom: "parent-work-zoom.png", chartId: ["histogram"]}],
        contextDescription: " Is it more common these days for dads to spend time with kids and work around the house? If so, is time spent that much different from decades past? How do dads’ times compare to moms’ times? An answer based on the American Time Use Survey that show hours spent with unpaid housework and childcare against hours spent at a job by moms and dads.",
        chartDescription: "2 interactive histograms with animated transition between datasets and control buttons on top.",
        tools: [{name: "javascript"}],
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 23,
        title: "Ukrain War: Poutine's assault organization",
        date: new Date(2022, 1),
        author: "Le Monde",
        url: "https://www.lemonde.fr/international/article/2022/02/25/guerre-en-ukraine-l-ordre-de-bataille-de-poutine_6115167_3210.html",
        img: [{full: "ukraine-attack-leMonde.jpeg", zoom: "ukraine-attack-leMonde-zoom.png", chartId: ["map"]}],
        contextDescription: "On the 24th of February Russian troops invaded Ukraine. <i>Le monde</i> created a full page on the topic based on a map of the area.",
        chartDescription: "Not really dataviz since this map does not display any data. But still interesting for design inspiration, notably for the whole page layout.",
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 24,
        title: "At least half a million refugees flee Ukraine",
        date: new Date(2022, 1),
        author: "The New York Times",
        url: "https://www.nytimes.com/interactive/2022/world/europe/ukraine-maps.html",
        img: [{full: "ukraine-migration-nyt.png", zoom: "ukraine-migration-nyt-zoom.png", chartId: ["map", "connection"]}],
        contextDescription: "The New York Times covered the migration of Ukrainians fleeing the war with a very complete article full of migration maps.",
        chartDescription: "This snapshot shows a sankey diagram drawn on top of a map. Read the article for more map examples.",
        luminosity: ["light"],
        interactive: true
    },
    {
        id: 25,
        title: "Big mac price",
        date: new Date(2021, 2),
        author: "Cédric Scherer",
        url: "https://www.r-graph-gallery.com/web-line-chart-with-labels-at-end-of-line.html",
        img: [{full: "big-mac-price.png", zoom: "big-mac-price-zoom.png", chartId: ["line"]}],
        contextDescription: "Compared to the fincancial crisis in 2008, how much more or less do you have to pay for a Big Mac today?",
        chartDescription: "A clean line chart allowing to compare the evolution of several groups. Note the clean inline legend that avoids the <a href='https://www.data-to-viz.com/caveat/spaghetti.html'>spaghetti effect</a>.",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-line-chart-with-labels-at-end-of-line.html"}, {name: "python", link:"https://python-graph-gallery.com/web-line-chart-with-labels-at-line-end"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 26,
        title: "Rouble tumbles to record low",
        date: new Date(2022, 1),
        author: "The New York Times",
        url: "https://www.nytimes.com/interactive/2022/world/europe/ukraine-maps.html",
        img: [{full: "rouble-tumbles-low.png", zoom: "rouble-tumbles-low-zoom.png", chartId: ["line"]}, {full: "rouble-tumbles-low.png", zoom: "rouble-tumbles-low-zoom-dark.png", chartId: ["line"]}],
        contextDescription: "A good proportion of the world countries have applied heavy sanctions to Russia following the Ukraine invasion. As a result the Rouble value is quickly decreasing.",
        chartDescription: "A line chart of the Ruble / USD exchange rate evolution. Two things are interesting here. Annotations are very clear and truly make a difference in the chart quality. The Y scale is inverted which is usually a bad thing, but works well here.",
        luminosity: ["light", "dark"],
        interactive: false
    },
    {
        id: 27,
        title: "Change in common household types",
        date: new Date(2022, 1),
        author: "Nathan Yau",
        url: "https://flowingdata.com/2022/03/01/change-in-common-household-types-in-the-u-s/",
        img: [{full: "household.png", zoom: "household-zoom.png", chartId: ["area"]}],
        contextDescription: "In the 1970s, the most common household type in the U.S. was a married couple with kids. But over time, as people wait longer to get married and have fewer kids (if any), it’s grown more common to live alone or with non-family.",
        chartDescription: "This project describes this kind of effect using an alluvial diagram, showing both the rank and the percentage of each household type over the years.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 28,
        title: "Decline in sex",
        date: new Date(2019, 3),
        author: "Washington Post",
        url: "https://www.washingtonpost.com/business/2019/03/29/share-americans-not-having-sex-has-reached-record-high/",
        img: [{full: "decline-sex.png", zoom: "decline-sex-zoom.png", chartId: ["line"]}],
        contextDescription: "The share of Americans not having sex has reached a record high. The washington post made a full article on the topic, explaining why this is mainly due to young people which sounds scary to me.",
        chartDescription: "A simple timeseries line chart showing the evolution of 2 groups (male and female). Note the on-chart annotation of both the group names and the current values.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 29,
        title: "Student exchanges in Europe",
        date: new Date(2022, 2),
        author: "Benjamin Nowak",
        url: "https://www.washingtonpost.com/business/2019/03/29/share-americans-not-having-sex-has-reached-record-high/",
        img: [{full: "student-exchance-europe.png", zoom: "student-exchance-europe-zoom.png", chartId: ["barplot"]}],
        contextDescription: "Erasmus is an exchange program allowing students to study abroad for a semester or more. This figure allows to see which countries are the most involved.",
        chartDescription: "The chart is a mirror barplot, showing both the number of outgoing and incoming students. I love the general layout and visual, even though I'm not sure about the opacity used to encode the year.",
        tools: [{name: "R", link:"https://t.co/LgnyJ3w63Y"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 30,
        title: "Sentiment in Russian tweets",
        date: new Date(2022, 2),
        author: "The Economist",
        url: "https://www.economist.com/graphic-detail/2022/03/12/the-war-in-ukraine-has-made-russian-social-media-users-glum",
        img: [{full: "sentiment-russia-twitter.png", zoom: "sentiment-russia-twitter-zoom.png", chartId: ["line"]}],
        contextDescription: "The war in Ukraine has made Russian social-media users glum. Posts on Twitter became far sadder than at the start of the covid-19 pandemic. A proof using sentiment analysis.",
        chartDescription: "A timeseries where evolution is represented using circles (average per day) and a line (7-day average). Having both information on the same figure is truly insightful. And the annotation of the outlier weeks help understand the full story.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 31,
        title: "Cat rescues by the London fire brigade",
        date: new Date(2021, 2),
        author: "Georgios Karamanis",
        url: "https://www.r-graph-gallery.com/web-time-series-and-facetting.html",
        img: [{full: "cat-rescues.png", zoom: "cat-rescues-zoom.png", chartId: ["line", "area"]}],
        contextDescription: "How many cats are rescued by the London fire brigade each year? How does it compare with other animals? An answer with data, split by suburbs",
        chartDescription: "Each item of the small multiple is a suburb. For each, we quickly see the number of cats (blue line) and other animals (red lines). Coloring the area between both in blue or red makes it easy to compare both at a higher scale.",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-time-series-and-facetting.html"}, {name: "python", link:"https://python-graph-gallery.com/web-time-series-and-facetting-with-matplotlib"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 32,
        title: "A world of language",
        date: new Date(2021, 8),
        author: "South China Morning Post",
        url: "https://www.scmp.com/infographics/article/1810040/infographic-world-languages",
        img: [{full: "world-of-language.png", zoom: "world-of-language-zoom.png", chartId: ["circularPacking"]}],
        contextDescription: "A deep look into the 7102 known languages alive in the world. What are the main ones? In which country are they spoken?",
        chartDescription: "A circular Voronoi diagram showing the importance of each language. So much information packed on the same figure, in a very eye-catching style.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 33,
        title: "Hong Kong and the Omicron variant",
        date: new Date(2022, 2),
        author: "the Financial Times",
        url: "https://www.scmp.com/infographics/article/1810040/infographic-world-languages",
        img: [{full: "hong-kong-omicron.png", zoom: "hong-kong-omicron-zoom.png", chartId: ["barplot"]}, {full: "hong-kong-omicron-2.png", zoom: "hong-kong-omicron-zoom-2.png", chartId: ["line"]}],
        contextDescription: "Hong Kong’s vaccination rate has lagged far behind peer countries, especially among the most vulnerable. This article by the financial times goes deep into this matter and compares the situation with other countries.",
        chartDescription: "Some timeseries line chart with clean on-graph legends and a set of 3 stacked bar chart clearly showing how Hong-Kong differs to other countries.",
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 34,
        title: "Topography of Switzerland",
        date: new Date(2022, 2),
        author: "Tobias Stalder",
        url: "https://twitter.com/toeb18/status/1503129088663433219",
        img: [{full: "switzerland-topography.png", zoom: "switzerland-topography-zoom.png", chartId: ["map"]}],
        contextDescription: "A transect from the Swiss Alps over the Swiss lowlands to the Jura mountains.",
        chartDescription: "A very clean 3D map made with R with a minigraph, very clean and concise.",
        tools: [{name: "R", link:"https://twitter.com/toeb18/status/1503129095433080838/photo/1"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 35,
        title: "Palmer Penguins",
        date: new Date(2021, 2),
        author: "Tuo Wang",
        url: "https://www.r-graph-gallery.com/web-scatterplot-and-ggrepel.html",
        img: [{full: "palmer-penguins.png", zoom: "palmer-penguins-zoom.png", chartId: ["scatter"]}],
        contextDescription: "Analyse the features of 3 penguins species: show the relationship between bill length and flipper length",
        chartDescription: "A custom scatterplot with auto-positioned labels to explore the palmerpenguins dataset made with R and the tidyverse.",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-scatterplot-and-ggrepel.html"}, {name: "python", link:"https://python-graph-gallery.com/web-text-repel-with-matplotlib"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 36,
        title: "Corruption and Human Development",
        date: new Date(2021, 2),
        author: "Claus O. Wilke",
        url: "https://www.r-graph-gallery.com/web-scatterplot-corruption-and-human-development.html",
        img: [{full: "corruption-hdi.png", zoom: "corruption-hdi-zoom.png", chartId: ["scatter"]}],
        contextDescription: "A scatterplot that shows the relationship between the Human Development Index and the Corruption Perceptions Index.",
        chartDescription: "A scatterplot with regression fit and automatic text repel. Relationship is striking.",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-scatterplot-corruption-and-human-development.html"}, {name: "python", link:"https://python-graph-gallery.com/web-scatterplot-text-annotation-and-regression-matplotlib"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 37,
        title: "Penguin Radar",
        date: new Date(2021, 2),
        author: "Tuo Wang",
        url: "https://www.r-graph-gallery.com/web-radar-chart-with-R.html",
        img: [{full: "penguin-radar.png", zoom: "penguin-radar-zoom.png", chartId: ["radar"]}],
        contextDescription: "Compares the bill length, bill debt, flipper length and body mass of 2 penguin species.",
        chartDescription: "A radar chart that compares the features of 3 groups for 4 numeric variables.",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-radar-chart-with-R.html"}, {name: "python", link:"https://python-graph-gallery.com/web-radar-chart-with-matplotlib"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 38,
        title: "Hiking locations in Washington",
        date: new Date(2021, 2),
        author: "Tobias Stadler",
        url: "https://www.r-graph-gallery.com/web-circular-barplot-with-R-and-ggplot2.html",
        img: [{full: "hiking-washington.png", zoom: "hiking-washington-zoom.png", chartId: ["circularBarplot"]}],
        contextDescription: "This Visualisation shows the cummulative length of tracks, the amount of tracks and the mean gain in elevation per location for a set of hikes in the Washington area.",
        chartDescription: "A circular barplot with clear group annotation, nice layout and great on-chart legend to explain what's shown.",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-circular-barplot-with-R-and-ggplot2.html"}, {name: "python", link:"https://python-graph-gallery.com/web-circular-barplot-with-matplotlib"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 39,
        title: "Child Labour",
        date: new Date(2021, 7),
        author: "The Economist",
        url: "https://www.r-graph-gallery.com/web-lineplots-and-area-chart-the-economist.html",
        img: [{full: "child-labour.png", zoom: "child-labour-zoom.png", chartId: ["line"]}, {full: "child-labour.png", zoom: "child-labour-zoom-2.png", chartId: ["area"]}],
        contextDescription: "A deep comparison of child labour across the globe.",
        chartDescription: "A line chart next to an area chart. Note that the first one is used for a percentage (does not make sense to add numbers up), when the second is used to a number where we are interested in the total number (stacking makes sense)",
        tools: [{name: "R", link:"https://www.r-graph-gallery.com/web-lineplots-and-area-chart-the-economist.html"}, {name: "python", link:"https://python-graph-gallery.com/web-lineplots-and-area-chart-the-economist"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 40,
        title: "Climate stripes",
        date: new Date(2018, 4),
        author: "Ed Hawkins",
        url: "https://showyourstripes.info/s/globe",
        img: [{full: "climate-stripes.png", zoom: "climate-stripes-zoom.png", chartId: ["heatmap"]}],
        contextDescription: "Warming stripes reflect a minimalist style, conceived to use colour alone to avoid technical distractions and intuitively convey global warming trends to non-scientists.",
        chartDescription: "Warming stripes (sometimes referred to as climate stripes, climate timelines or stripe graphics are data visualization graphics that use a series of coloured stripes chronologically ordered to visually portray long-term temperature trends.",
        tools: undefined,
        luminosity: ["light", "dark"],
        interactive: false
    },
    {
        id: 41,
        title: "Violin & Boxplot with ggplot2",
        date: new Date(2018, 4),
        author: "Yan Holtz",
        url: "https://www.data-to-viz.com/graph/violin.html",
        img: [{full: "violin-boxplot-ggplot2.png", zoom: "violin-boxplot-ggplot2-zoom.png", chartId: ["violin", "boxplot"]}],
        contextDescription: "A boxplot can hide the real underlying distribution of a set of data. The violin chart is a great alternative.",
        chartDescription: "Combination of a violin plot with a boxplot. Sample size added on the x axis. Build with ggplot2.",
        tools: [{name: "R", link:"https://www.data-to-viz.com/graph/violin.html"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 42,
        title: "Vaccine and FDA approval",
        date: new Date(2021, 7),
        author: "The Wall Street Journal",
        url: "https://www.wsj.com/articles/covid-19-vaccinations-rise-as-delta-variant-spreads-pfizer-receives-full-fda-approval-11629905741",
        img: [{full: "vaccine-fda-approval.png", zoom: "vaccine-fda-approval-zoom.png", chartId: ["waffle"]}],
        contextDescription: "The whole planet is trying to get vaccinated. Some people don't want to. Does an FDA approval would convince them?",
        chartDescription: "Using 3 waffle charts to compare 3 proportions.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 43,
        title: "Violin chart - Seaborn",
        date: new Date(2018, 1),
        author: "Yan Holtz",
        url: "https://python-graph-gallery.com/violin-plot/",
        img: [{full: "violin-seaborn.png", zoom: "violin-seaborn-zoom.png", chartId: ["violin"]}],
        contextDescription: "Random data are used here.",
        chartDescription: "This example just shows the default style of the Seaborn Python library.",
        tools: [{name: "python", link:"https://python-graph-gallery.com/violin-plot/"}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 44,
        title: "revenues compared to pre-pandemic",
        date: new Date(2018, 1),
        author: "The Wall Street Journal",
        url: "https://www.wsj.com/articles/how-the-biggest-companies-have-fared-during-the-covid-19-pandemic-11630229403?st=ntrtz9fpufqjchy&reflink=share_mobilewebshare",
        img: [{full: "revenu-pre-pandemic.png", zoom: "revenu-pre-pandemic-zoom.png", chartId: ["scatter"]}],
        contextDescription: "Covid19 Pandemic got a massive impact on some company revenues. This chart studies how revenues evolved during and after the pandemic.",
        chartDescription: "A Scatterplot that split the graph area in 4 sections, showing 4 potential behaviour of companies. As often, single data points are labeled to understand what are the most important data points.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 45,
        title: "Control of states",
        date: new Date(2021, 5),
        author: "Washington Post",
        url: "https://www.washingtonpost.com/politics/interactive/2021/redistricting-faq/",
        img: [{full: "control-of-states.png", zoom: "control-of-states-zoom.png", chartId: ["parallel"]}],
        contextDescription: "How many states are controled by which party in the US. How did it change between 2010 and 2020?",
        chartDescription: "Two parallel charts showing the evolution of each political party, measured by state and by districts.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 46,
        title: "Piano Notes",
        date: new Date(2022, 2),
        author: "Alice Feng",
        url: "https://www.behance.net/gallery/139799525/Piano-Notes",
        img: [{full: "piano-notes.png", zoom: "piano-notes-zoom.png", chartId: ["bubble"]}],
        contextDescription: "A visualization of what parts of the piano keyboard are played the most in well-known classical music pieces.",
        chartDescription: "A bubble chart where the Y axis is a categoric variable. Very clean design, with an extensive legend.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 47,
        title: "The Art of the High Line",
        date: new Date(2016, 2),
        author: "Studio Terp",
        url: "https://www.studioterp.nl/the-art-of-the-high-line/",
        img: [{full: "art-of-the-high-line.png", zoom: "art-of-the-high-line-zoom.png", chartId: ["bubble"]}],
        contextDescription: "<a href='https://www.thehighline.org'>The High Line</a> is a elevated linear park in New York that showcases the work of artists. This viz describes the artists that have been exposed there.",
        chartDescription: "This piece is mainly a circular barplot. But it manages to store a massive amount of information thanks to the inner circles supplementary charts.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 48,
        title: "Carbon Tax",
        date: new Date(2016, 2),
        author: "Studio Terp",
        url: "http://www.studioterp.nl/carbon-taxes-a-datavisualization-for-scientific-american/",
        img: [{full: "carbon-tax.png", zoom: "carbon-tax-zoom.png", chartId: []}],
        contextDescription: "This viz compares carbon tax features of several countries. It checks the revenue, the tax rate and the emmisioins portion covered by Tax.",
        chartDescription: "It's hard to classify this poster in a viz type. Each country is represented by several shapes, with shape size mapped to a numeric variable. Small multiples is used here to showcases all countries.",
        tools: undefined,
        luminosity: ["light"],
        interactive: false
    },
    {
        id: 49,
        title: "Squashing Malaria",
        date: new Date(2017, 2),
        author: "Beautiful News Daily",
        url: "https://informationisbeautiful.net/beautifulnews/1172-africa-squashing-malaria/",
        img: [{full: "squashing-malaria.png", zoom: "squashing-malaria-zoom.png", chartId: ["parallel"]}],
        contextDescription: "90% of malaria cases occur in Africa. That’s 200m infections and 400,000 deaths, mainly children under the age of 5. But the numbers are falling.",
        chartDescription: "A slope chart showing the # of cases per 1000 people in 2007 and 2017 for several African countries. A good way to highlight the global decrease while ranking the countries.",
        tools: undefined,
        luminosity: ["light", "dark"],
        interactive: false
    },
    {
        id: 50,
        title: "Cycling to work",
        date: new Date(2017, 2),
        author: "Beautiful News Daily",
        url: "https://informationisbeautiful.net/beautifulnews/614-cycling-to-work/",
        img: [{full: "cycling-to-work.png", zoom: "cycling-to-work-zoom.png", chartId: ["circularPacking"]}],
        contextDescription: "Cycling is getting more and more popular on planet earth. This viz checks what are the cities with most bicycle commuters.",
        chartDescription: "A circular packing chart with one level of information. Each bubble map is sized according to its proportion of bicycle commuters. I'm not a big fan of the gradient effect though.",
        tools: undefined,
        luminosity: ["light", "dark"],
        interactive: false
    },
    {
        id: 51,
        title: "Global weather conditions",
        date: new Date(2013, 11),
        author: "Cameron Beccario",
        url: "https://earth.nullschool.net",
        img: [{full: "global-weather-conditions.png", zoom: "global-weather-conditions-zoom.png", chartId: ["map"]}],
        contextDescription: "An animated map of global weather conditions. Includes wind, waves, temperature and much more. Show real time data.",
        chartDescription: "An interactive map showing global flows. You can rotate and zoom the globe. I like how the webpage is viz focused, with an optional control panel to decide what to display.",
        tools: [{name: "javascript", link: "https://github.com/cambecc/earth"}],
        luminosity: [ "dark"],
        interactive: true
    },
    {
        id: 52,
        title: "Wind Map",
        date: new Date(2012, 9),
        author: "F. Viégas and M. Wattenberg ",
        url: "http://hint.fm/wind/",
        img: [{full: "wind-map.png", zoom: "wind-map-zoom.png", chartId: ["map"]}],
        contextDescription: "A novel way to observe how wind blows on a geographical area. This work inspired Cameron Beccario to create the <a href='https://earth.nullschool.net'>Global Weather Conditions</a> app.",
        chartDescription: "Please read <a href='https://www.earthisland.org/journal/index.php/articles/entry/imagining-the-wind'>this article</a> that explains how this project was born and what impact it had.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 53,
        title: "Running stats",
        date: new Date(2020, 9),
        author: "Unknown",
        url: "https://analyticsindiamag.com/7-types-of-tableau-charts-graphs-to-make-your-data-visually-interactive/",
        img: [{full: "running-stats.png", zoom: "running-stats-zoom-1.png", chartId: ["line", "area"]}, {full: "running-stats.png", zoom: "running-stats-zoom-2.png", chartId: ["histogram"]}, {full: "running-stats.png", zoom: "running-stats-zoom-3.png", chartId: ["histogram"]}, {full: "running-stats.png", zoom: "running-stats-zoom-4.png", chartId: ["barplot"]}],
        contextDescription: "A few vizzes giving running stats. I do not have more details on the project, this is just a snapshot",
        chartDescription: "I don't know much about this project, but wanted to show it for its slick design. Be careful, the radial barchart is definitely not a good viz type.",
        tools: undefined,
        luminosity: [ "light", "dark"],
        interactive: false
    },
    {
        id: 54,
        title: "Codebase visualization",
        date: new Date(2021, 9),
        author: "Amelia Wattenberger",
        url: "https://next.github.com/projects/repo-visualization/",
        img: [{full: "codebase-viz.png", zoom: "codebase-viz-zoom.png", chartId: ["circularPacking"]}],
        contextDescription: "A project by github that takes a repository and visualize its content. Each circle is a folder containing sub-folders, down until files.",
        chartDescription: "Two things I really love on this circular packing project: the way labels are set around each circles, and the scrolly-telling that works like a charm.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 55,
        title: "Where are Americans born",
        date: new Date(2022, 1),
        author: "Erin",
        url: "https://erdavis.com/2022/02/09/how-i-made-the-viral-map/",
        img: [{full: "american-born.png", zoom: "american-born-zoom.png", chartId: ["map"]}],
        contextDescription: "Where does citizen of each US state come from? Where they born in this state? Or are they from abroad?",
        chartDescription: "A small multiple map that quickly conveys a pretty complicated information. No wonders it became viral on <a href='https://twitter.com/erindataviz/status/1489009794245541888?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1489009794245541888%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Ferdavis.com%2F2022%2F02%2F09%2Fhow-i-made-the-viral-map%2F'>twitter</a>!",
        tools: [{name: "R", link: "https://erdavis.com/2022/02/09/how-i-made-the-viral-map/"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 56,
        title: "Art, Women posing and upvotes",
        date: new Date(2021, 5),
        author: "Erin",
        url: "https://erdavis.com/2021/06/14/do-women-who-pose-with-their-art-on-reddit-get-more-upvotes/",
        img: [{full: "art-women-posing-1.png", zoom: "art-women-posing-zoom-1.png", chartId: ["line"]}, {full: "art-women-posing-2.png", zoom: "art-women-posing-zoom-2.png", chartId: ["density"]}],
        contextDescription: "Do women who pose with their art on Reddit get more upvotes? Erin gathered reddit data on the topic to proove that yes, posing with your art helps getting upvoted, especially if you're a woman.",
        chartDescription: "Erin's article is well written and vizzes are unusual and very well thought. A masterpiece of data analysis!",
        tools: [{name: "R", link: "https://erdavis.com/2021/06/14/do-women-who-pose-with-their-art-on-reddit-get-more-upvotes/"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 57,
        title: "Obama’s 2013 Budget Proposal",
        date: new Date(2012, 1),
        author: "The New York Times",
        url: "https://archive.nytimes.com/www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html?",
        img: [{full: "obama-budget-proposal.png", zoom: "obama-budget-proposal-zoom.png", chartId: ["circularPacking"]}],
        contextDescription: "An interactive visualization of the Obama's budget proposal. A powerful way to see where the money should go based on Obama's opinion.",
        chartDescription: "An interactive circle packing chart with great tooltip. The transitions between viz types are very smooth and make it a delight to explore.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 58,
        title: "French presidential election",
        date: new Date(2022, 2),
        author: "Le Monde",
        url: "https://www.lemonde.fr/les-decodeurs/article/2022/02/22/presidentielle-2022-le-tableau-de-bord-des-parrainages-sondages-et-temps-de-parole_6114816_4355770.html",
        img: [{full: "french-presidential-election-1.png", zoom: "french-presidential-election-zoom-1.png", chartId: ["barplot"]}, {full: "french-presidential-election-2.png", zoom: "french-presidential-election-zoom-2.png", chartId: ["scatter"]}, {full: "french-presidential-election-3.png", zoom: "french-presidential-election-zoom-3.png", chartId: ["bubbleMap"]}],
        contextDescription: "French presidential elections are happening soon. <i>Le Monde</i> wrote a in-depth article showing some of the candidate features: who talks the most on media, who's the richest, who has the best chances to win according to polls?",
        chartDescription: "A data-based article with clean design. I mainly selected it for the clean horizontal barplots that can probably be used on other projects.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 59,
        title: "The Spread of QAnon",
        date: new Date(2022, 2),
        author: "Cédric Scherer",
        url: "https://cemas.io/en/publikationen/q-vadis-the-spread-of-qanon-in-the-german-speaking-world/CeMAS_Q_Vadis_The_Spread_of_QAnon_in_the_German-Speaking_World.pdf",
        img: [
            {full: "spread-of-qanon-1.png", zoom: "spread-of-qanon-zoom-1.png", chartId: ["stream"]},
            {full: "spread-of-qanon-2.png", zoom: "spread-of-qanon-zoom-2.png", chartId: ["barplot"]},
            {full: "spread-of-qanon-3.png", zoom: "spread-of-qanon-zoom-3.png", chartId: ["area"]}],
        contextDescription: "The central piece of a study on the spread of QAnon in the german-speaking world. It shows the amount of QAnon related messages exchanged on Telegram.",
        chartDescription: "A massive streamchart showing the raise of QAnon on private channels, with a spike next to the Storming of the Capitol. In the printed version this viz is folded in 4 parts.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 60,
        title: "Worst & Highest paid NBA player",
        date: new Date(2019, 11),
        author: "The Pudding",
        url: "https://pudding.cool/2019/12/real-mvp/",
        img: [{full: "worst-paid-nba-player.png", zoom: "worst-paid-nba-player-zoom.png", chartId: ["scatter"]}],
        contextDescription: "Using advanced NBA stats to rank player performance against pay.",
        chartDescription: "A colorfull scatterplot with gradient. Original design choices, especially when it comes to the axes.",
        tools: undefined,
        luminosity: [ "dark"],
        interactive: false
    },
    {
        id: 61,
        title: "Airports and world's megacities",
        date: new Date(2018, 6),
        author: "The Pudding",
        url: "https://pudding.cool/2018/07/airports/",
        img: [
            {full: "airport-world-megacities-1.png", zoom: "airport-world-megacities-zoom-1.png", chartId: ["connection"]},
            {full: "airport-world-megacities-2.png", zoom: "airport-world-megacities-zoom-2.png", chartId: ["barplot"]},
            {full: "airport-world-megacities-3.png", zoom: "airport-world-megacities-zoom-3.png", chartId: ["connectedScatter"]},
            {full: "airport-world-megacities-4.png", zoom: "airport-world-megacities-zoom-4.png", chartId: ["scatter"]}
        ],
        contextDescription: "Biggest cities tend to have more departing flights per day. But some cities don't follow the trend. This data-based article try to explains it.",
        chartDescription: "A set of charts following the same design, spread around a well-written article. I really like the mirror barplot and the clear annotations that make the vizs very insightful.",
        tools: undefined,
        luminosity: [ "dark"],
        interactive: false
    },
    {
        id: 62,
        title: "Eating alone",
        date: new Date(2017, 6),
        author: "The Pudding",
        url: "https://pudding.cool/2017/07/eating-alone/",
        img: [
            {full: "eating-alone-1.png", zoom: "eating-alone-zoom-1.png", chartId: ["scatter", "line"]},
            {full: "eating-alone-2.png", zoom: "eating-alone-zoom-2.png", chartId: ["lollipop"]}
        ],
        contextDescription: "An exploration of the dining habits and companions of Americans.",
        chartDescription: "A nicely animate scatterplot with linear trend. The page uses scrollytelling, progressively adding features to the chart as the story goes.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 63,
        title: "Rigid middle class?",
        date: new Date(2020, 7),
        author: "The Pudding",
        url: "https://pudding.cool/2020/08/income/",
        img: [
            {full: "rigid-middle-class.png", zoom: "rigid-middle-class-zoom.png", chartId: ["barplot"]},
        ],
        contextDescription: "If you were to ask random Americans what income class they fall into, there’s a good chance they’ll say “middle class”. But what does that mean?",
        chartDescription: "Three colorfull barplots allowing to compare features of 3 groups. The article uses scrollytelling.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 64,
        title: "What is Congress tweeting about?",
        date: new Date(2020, 7),
        author: "The Pudding",
        url: "https://congress.pudding.cool",
        img: [
            {full: "congress-tweeting-1.png", zoom: "congress-tweeting-zoom-1.png", chartId: ["barplot", "treemap"]},
            {full: "congress-tweeting-2.png", zoom: "congress-tweeting-zoom-2.png", chartId: ["area", "line"]},
            {full: "congress-tweeting-3.png", zoom: "congress-tweeting-zoom-3.png", chartId: ["hexbin", "map"]},
        ],
        contextDescription: "An article describing the topics that dominate members of Congress public discourse.",
        chartDescription: "A complete app with various chart types showing different features of the dataset. Nice design and consistent styling and palettes among charts.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 65,
        title: "Switching between phone brands",
        date: new Date(2014, 11),
        author: "Nadieh Bremer",
        url: "https://nbremer.github.io/Chord-Diagram-Storytelling/",
        img: [
            {full: "switching-phone-1.png", zoom: "switching-phone-zoom-1.png", chartId: ["chordDiagram"]},
            {full: "switching-phone-2.png", zoom: "switching-phone-zoom-2.png", chartId: ["chordDiagram"]},
        ],
        contextDescription: "A study asked 2000 residents of the Netherlands about their mobile phone behavior. The respondents gave information about the brand of their current main phone, and the brand of their previous main phone, and their answers are visualized in this data story.",
        chartDescription: "Probably the best chord diagram example I know so far. The project incrementally add each part of the final figure to explain how it works.",
        tools: [{name: "d3.js", link: "https://github.com/nbremer/Chord-Diagram-Storytelling"}],
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 66,
        title: "Satellite Surge",
        date: new Date(2020, 1),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/sciam-satellite-surge/",
        img: [
            {full: "satellite-surge.png", zoom: "satellite-surge-zoom.png", chartId: ["stream"]},
        ],
        contextDescription: "A visualization showing the rise and recent surge of the number of satellites that orbit Earth for the “Graphic Science” magazine.",
        chartDescription: "A vertical streamgraph with a lot of annotations telling the story. Note that each group of the stream are divided in substreams that follow a 'bump chart' logic.",
        tools: [{name: "d3.js", link: undefined}, {name: "R", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 67,
        title: "Digital Trackers",
        date: new Date(2019, 7),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/new-york-times-digital-trackers/",
        img: [
            {full: "digital-tracker.png", zoom: "digital-tracker-zoom.png", chartId: ["network", "circularPacking"]},
        ],
        contextDescription: "Visualizing the insane number of digital trackers that you gather when you browse the web for the new York times.",
        chartDescription: "This is not exactly a network chart but more a diagram representing the day of a regular internet user. The design is very clean and definitely worth a read.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 68,
        title: "Frontex: EU’s Deportation Machine",
        date: new Date(2019, 6),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/lighthouse-reports-frontex/",
        img: [
            {full: "frontex-deportation-1.png", zoom: "frontex-deportation-zoom-1.png", chartId: ["connection"]},
            {full: "frontex-deportation-1.png", zoom: "frontex-deportation-zoom-2.png", chartId: ["area"]},
        ],
        contextDescription: "Frontex is the EU coast and border agency. It is in charge of organizing the flights that send deportees back home. This viz shows this sad flow on the globe.",
        chartDescription: "The static version already does a great job at showing the flow thanks to subtle color gradients and icons. But the <a href='https://vimeo.com/351673775'>video</a> is definitely worth a look to, as it depict the acceleration of the process in another way.",
        tools: [{name: "d3.js", link: undefined}, {name: "R", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 69,
        title: "Shareholder Report",
        date: new Date(2019, 1),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/adyen-report-2019/",
        img: [
            {full: "shareholder-report-1.png", zoom: "shareholder-report-zoom-1.png", chartId: ["sankey"]},
            {full: "shareholder-report-2.png", zoom: "shareholder-report-zoom-2.png", chartId: ["treemap"]},
            {full: "shareholder-report-3.png", zoom: "shareholder-report-zoom-3.png", chartId: ["waffle"]},
        ],
        contextDescription: "Some figures for a shareholder letter & annual report. Four extensive visuals about the income statement, costs, regional and FTE growth.",
        chartDescription: "Several chart types following the same design guidelines: sankey, treemap and waffle. I really like that they each have their own personal touch: sankey start with a gradient, treemap and waffle items have a 45° rotation.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 70,
        title: "Intangible Cultural Heritage",
        date: new Date(2018, 9),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/intangible-cultural-heritage/",
        img: [
            {full: "cultural-heritage.png", zoom: "cultural-heritage-zoom.png", chartId: ["network"]},
        ],
        contextDescription: "Since 2003 UNESCO safeguards an ever growing list of our Intangible Cultural Heritage and these days there are almost 500 unique cultural elements inscribed on the list.",
        chartDescription: "A network chart showing those cultural heritage items and their connections. The interactive version is <a href='https://ich.unesco.org/en/dive&display=constellation#tabs'>available here</a>.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 71,
        title: "Bussed out",
        date: new Date(2017, 11),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/bussed-out/",
        img: [
            {full: "bussed-out-1.png", zoom: "bussed-out-zoom-1.png", chartId: ["density"]},
            {full: "bussed-out-2.png", zoom: "bussed-out-zoom-2.png", chartId: ["bubbleMap"]},
            {full: "bussed-out-3.png", zoom: "bussed-out-zoom-3.png", chartId: ["arc"]},
        ],
        contextDescription: "Each year, US cities give thousands of homeless people one-way bus tickets out of town. An 18-month nationwide investigation by the Guardian reveals, for the first time, what really happens at journey’s end.",
        chartDescription: "A master piece of scrollytelling feature a wide range of viz types. I am a big fan of the vertical density chart with this flow diagram on the left, beautiful.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 72,
        title: "Baby spike",
        date: new Date(2017, 3),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/baby-spike/",
        img: [
            {full: "baby-spike.png", zoom: "baby-spike-zoom.png", chartId: ["density"]}
        ],
        contextDescription: "Visualizing the number of babies born across different time frames; from weeks down to the minute, to reveal the role of scheduling & intervention in births.",
        chartDescription: "Those density charts are highly customized. They are made circular to show the cyclic nature of the data. The distribution is also spread around the median line, instead of using 0 as a baseline.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 73,
        title: "Words in the Lord of the Rings",
        date: new Date(2016, 6),
        author: "Nadieh Bremer",
        url: "https://www.visualcinnamon.com/portfolio/words-lord-of-the-rings/",
        img: [
            {full: "lord-of-rings-words.png", zoom: "lord-of-rings-words-zoom.png", chartId: ["chordDiagram", "sankey"]}
        ],
        contextDescription: "In this visualization you can find out how many words a member of the lord of the rings has spoken at each different location throughout the trilogy.",
        chartDescription: "This chart is looking a lot like a chord diagram but has nodes in the center of the figures. Check the <a href='https://lotr.visualcinnamon.com'>interactive version</a> for a better exploration.",
        tools: [{name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 74,
        title: "Annual working hours",
        date: new Date(2022, 3),
        author: "Ansgar Wolsing",
        url: "https://github.com/bydata/30DayChartChallenge/blob/main/2022/06/06-owid-slope.png",
        img: [
            {full: "annual-workinf-hours.png", zoom: "annual-workinf-hours-zoom.png", chartId: ["parallel"]}
        ],
        contextDescription: "In this visualization you can find out how many words a member of the lord of the rings has spoken at each different location throughout the trilogy.",
        chartDescription: "Just a clean parallel chart. Great way to legend the chart using an inline color in the chart explanation on top.",
        tools: [{name: "R", link: 'https://github.com/bydata/30DayChartChallenge/blob/main/2022/06/06-owid-slope.png'}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 75,
        title: "FM Radios",
        date: new Date(2020, 3),
        author: "Erin",
        url: "https://erdavis.com/2020/01/04/visualizing-the-geography-of-fm-radio/",
        img: [
            {full: "fm-radios-map.png", zoom: "fm-radios-map-zoom.png", chartId: ["bubbleMap", "map"]}
        ],
        contextDescription: "Checking where FM radios are broadcasting from, split by type.",
        chartDescription: "Probably more data art than data viz but I very like the global style of this map.",
        tools: undefined,
        luminosity: [ "dark"],
        interactive: false
    },
    {
        id: 76,
        title: "Upvotes are beautiful",
        date: new Date(2020, 2),
        author: "Erin",
        url: "https://erdavis.com/2020/03/17/6-weeks-of-activity-on-dataisbeautiful-also-coronavirus/",
        img: [
            {full: "upvotes-are-beautiful.png", zoom: "upvotes-are-beautiful-zoom.png", chartId: ["line", "connectedScatter", "timeseries"]}
        ],
        contextDescription: "Some awesome viz are posted on Reddit every day, on a channel called <a href='https://www.reddit.com/r/dataisbeautiful/'>DataIsBeautiful</a>. This viz checks how popular each viz became for a month. Only a few per day make it to popularity!",
        chartDescription: "This is a very specific grouped line chart. There are many groups. The value can only increase and data is recorded for 36 hours only. It results in a very original shape. The annotation on top allow to learn what titles where the most popular.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 77,
        title: "Hidden logic of cities",
        date: new Date(2019, 8),
        author: "Erin",
        url: "https://erdavis.com/2019/09/20/the-beautiful-hidden-logic-of-cities-worldwide/",
        img: [
            {full: "hidden-logic-of-cities.png", zoom: "hidden-logic-of-cities-zoom.png", chartId: ["map"]}
        ],
        contextDescription: "Driving around your city, you’re probably somewhat aware of Avenues and Boulevards and Streets and Roads and so on. This project aims at showing where each type takes place.",
        chartDescription: "Those map are just representing what kind of area each place is (street, place, river..). A bunch of cities are available as prints <a href='https://society6.com/erdavis'>here</a>.",
        tools: [{name: "R", link: "https://github.com/erdavis1/RoadColors"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 78,
        title: "Mapping road intersections",
        date: new Date(2020, 6),
        author: "Erin",
        url: "https://erdavis.com/2020/07/06/how-common-are-roundabouts-plus-a-bunch-of-other-maps/",
        img: [
            {full: "road-intersections.png", zoom: "road-intersections-zoom.png", chartId: ["map"]}
        ],
        contextDescription: "A project that maps the 34 million road intersections in Europe. Visit the project to see other great images about roundabouts and empty places.",
        chartDescription: "It's important to understand that the process results in a population density map. But the “city lights from space” + “starry sky” effect is definitely working here.",
        tools: undefined,
        luminosity: [ "dark"],
        interactive: false
    },
    {
        id: 79,
        title: "Reading list",
        date: new Date(2020, 6),
        author: "Erin",
        url: "https://erdavis.com/2022/01/04/my-2021-in-reading/",
        img: [
            {full: "reading-list.png", zoom: "reading-list-zoom.png", chartId: ["line", "timeseries"]}
        ],
        contextDescription: "The author read a bunch of book in 2021, and track the progress of each book along the year. This viz allows to see which book she was reading at each period of the year.",
        chartDescription: "In my opinion this is a very clever way to represent this dataset. It allows to have a very global vision of the year, and to see which book behaviour. Check how Sapiens became a struggle, I did not finish it either!",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 80,
        title: "Genome collection",
        date: new Date(2021, 6),
        author: "Maarten Lambrechts",
        url: "https://www.maartenlambrechts.com/2021/07/02/visualizing-a-genome-collection-with-cactustrees.html",
        img: [
            {full: "genome-collection-1.png", zoom: "genome-collection-zoom-1.png", chartId: ["dendrogram"]},
            {full: "genome-collection-2.png", zoom: "genome-collection-zoom-2.png", chartId: ["network"]},
            {full: "genome-collection-3.png", zoom: "genome-collection-zoom-3.png", chartId: ["edgeBundling", "network"]},
        ],
        contextDescription: "How do you visualize a genome collection of more than 44.000 soil microbes? A project that takes gene sequences of different kinds of soil organisms, and tries to find species and specimens that are biologically active against crop pests.",
        chartDescription: "This final piece of this project is a <a href='http://ceur-ws.org/Vol-1947/paper05.pdf'>Cactus Trees</a> visualization, a kind I did not know until today. The author explains the full process leading there, an interesting read and some unconventional shapes.",
        tools: [{name: "R", link: undefined}, {name: "d3.js", link: undefined}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 81,
        title: "Bundling on map",
        date: new Date(2021, 6),
        author: "Holten et al.",
        url: "https://www.data-to-viz.com/graph/edge_bundling.html",
        img: [
            {full: "map-bundling.png", zoom: "map-bundling-zoom.png", chartId: ["map", "edgeBundling", "connection"]},
        ],
        contextDescription: "This figure is part of a paper called 'Force-Directed Edge Bundling for Graph Visualization'. It represents the US airlines connections and studies a variety of bundling algorithms.",
        chartDescription: "You can read the complete research paper <a href='https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.212.7989&rep=rep1&type=pdf'>here</a>, that compares different values for the bundling. It shows very well how useful can be bundling.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 82,
        title: "Co-autorship network",
        date: new Date(2018, 6),
        author: "Yan Holtz",
        url: "https://www.data-to-viz.com/graph/arc.html",
        img: [
            {full: "co-autorship-network.png", zoom: "co-autorship-network-zoom.png", chartId: ["arc"]},
        ],
        contextDescription: "An example showing the co-authorship network of a researcher. Vincent Ranwez is author of several scientific publications and counts more than 100 co-authors. How are those co-authors interconnected?",
        chartDescription: "Vincent Ranwez has about 100 co-authors, all represented by a node on the following chart. If two people have already been on the same paper, they are linked by an arc.",
        tools: [{name: "R", link: "https://www.data-to-viz.com/graph/arc.html"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 83,
        title: "Metal recovery",
        date: new Date(2012, 6),
        author: "Golev et al.",
        url: "https://www.data-to-viz.com/graph/sankey.html",
        img: [
            {full: "metal-recovery.png", zoom: "metal-recovery-zoom.png", chartId: ["sankey"]},
        ],
        contextDescription: "A sankey diagram showing the flow of metals in Australia. Import, Export, waste, all the in and out are included.",
        chartDescription: "Clean and un-cluttered design for this Sankey diagram.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 84,
        title: "Migraton flow",
        date: new Date(2018, 6),
        author: "Gui J. Abel",
        url: "https://www.data-to-viz.com/graph/chord.html",
        img: [
            {full: "migration-flow.png", zoom: "migration-flow-zoom.png", chartId: ["chordDiagram"]},
        ],
        contextDescription: "Everyday, people leave a country to join another, creating migration flows. This img is a reproduction of a figure from this <a href='https://onlinelibrary.wiley.com/doi/abs/10.1111/imre.12327'>scientific paper</a> that studies those flows.",
        chartDescription: "An insightful chord diagram showing migration flows between continent. I really like how easy it is to understand the direction of the flow thanks to the arrow and the start vs end position shift of the connection.",
        tools: [{name: "R", link: "https://www.data-to-viz.com/graph/chord.html"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 85,
        title: "EU Regions",
        date: new Date(2019, 3),
        author: "Maarten Lambrechts",
        url: "https://pudding.cool/2019/04/eu-regions/",
        img: [
            {full: "eu-regions-1.png", zoom: "eu-regions-zoom-1.png", chartId: ["map", "choropleth"]},
            {full: "eu-regions-2.png", zoom: "eu-regions-zoom-2.png", chartId: ["lollipop", "scatter"]},
        ],
        contextDescription: "A in-depth analysis of the european regions. It tries to explain why Budapest, Warsaw, and Lithuania split themselves in two.",
        chartDescription: "The choropleth map presented in this scrolltelling article is very clean, and so are the animations telling the story. Definitely worth checking the whole <a href='https://pudding.cool/2019/04/eu-regions/'>interactive project</a>, at least for the choropleth to lollipop transition.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 86,
        title: "Animated treemap",
        date: new Date(2019, 3),
        author: "Maarten Lambrechts",
        url: "https://themasites.pbl.nl/o/duurzaam-voedsel/",
        img: [
            {full: "animated-treemap.png", zoom: "animated-treemap-zoom.png", chartId: ["treemap"]},
        ],
        contextDescription: "Not sure about the context of this chart, it's all written in flamish 😀 .",
        chartDescription: "Clean treemap with illustrations. The transition between dataset is nice in the first tries, but then feels a bit long when you keep playing with it.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 87,
        title: "Eurosearch song contest",
        date: new Date(2019, 3),
        author: "Maarten Lambrechts",
        url: "https://googletrends.github.io/eurosearch-song-contest/",
        img: [
            {full: "eurosearch-song-contest.png", zoom: "eurosearch-song-contest-zoom.png", chartId: ["map", "hexbin"]},
        ],
        contextDescription: "What if Google searches were used to award points in the Eurovision Song Contest? What countries would make the final and who would cry victory?",
        chartDescription: "Many countries are small, sometimes barely visible on the map. But they're value is worth as much as big countries. This article suggests to squarify Europe to put all countries on the same scale.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 88,
        title: "The 200+ beer brands",
        date: new Date(2015, 9),
        author: "Maarten Lambrechts",
        url: "https://www.maartenlambrechts.com/2015/10/16/interactive-the-200-beer-brands-of-sab-inbev.html",
        img: [
            {full: "the-200-beer-brands.png", zoom: "the-200-beer-brands-zoom.png", chartId: ["dendrogram"]},
        ],
        contextDescription: "The merging of AB InBev and SABMiller creates a brewing giant, more than one third of all beer worldwide will be produced by just one company. Here is an overview of all the beers that are concerned.",
        chartDescription: "This is a radial dendrogram, where beers are subdivided in continent and country. Fun interactive touch: hovering a beer makes you see the bottle. Made me thirsty 🌴 !",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 89,
        title: "Who speaks when in Shakespeare's MacBeth?",
        date: new Date(2022, 3),
        author: "Ansgar Wolsing",
        url: "https://github.com/bydata/30DayChartChallenge/tree/main/2022/10",
        img: [
            {full: "who-speaks-in-shakespeare.png", zoom: "who-speaks-in-shakespeare-zoom.png", chartId: ["stream"]},
        ],
        contextDescription: "Distribution of speech share (number of words) per character in each scene. Acts are separated with vertical lines.",
        chartDescription: "A dark mode streamgraph with clean annotations.",
        tools: [{name: "R", link: "https://github.com/bydata/30DayChartChallenge/tree/main/2022/10"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 90,
        title: "Mortality and mental disorders",
        date: new Date(2018, 3),
        author: "Yan Holtz",
        url: "https://holtzy.github.io/Mortality/",
        img: [
            {full: "mortality-and-mental-disorders-1.png", zoom: "mortality-and-mental-disorders-zoom-1.png", chartId: ["line"]},
            {full: "mortality-and-mental-disorders-2.png", zoom: "mortality-and-mental-disorders-zoom-2.png", chartId: ["lollipop"]},
            {full: "mortality-and-mental-disorders-3.png", zoom: "mortality-and-mental-disorders-zoom-3.png", chartId: ["barplot"]},
        ],
        contextDescription: "An interactive webpage that goes along with a <a href='https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(19)32316-5/fulltext'>scientific publication</a>. The goal was to study the links between mortality rates and mental disorders.",
        chartDescription: "The webpage includes several chart types, all with buttons allowing to control what part of the dataset is displayed. It is a mix between a data storytelling and a data exploration tool.",
        tools: [{name: "d3.js", link: "https://github.com/holtzy/Mortality"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 91,
        title: "The World Mental Health Survey",
        date: new Date(2018, 3),
        author: "Yan Holtz",
        url: "https://holtzy.github.io/Mortality/",
        img: [
            {full: "world-mental-health-survey-1.png", zoom: "world-mental-health-survey-zoom-1.png", chartId: ["heatmap"]},
            {full: "world-mental-health-survey-2.png", zoom: "world-mental-health-survey-zoom-2.png", chartId: ["barplot"]},
            {full: "world-mental-health-survey-3.png", zoom: "world-mental-health-survey-zoom-3.png", chartId: ["sankey"]},
            {full: "world-mental-health-survey-4.png", zoom: "world-mental-health-survey-zoom-4.png", chartId: ["line"]},
        ],
        contextDescription: "A set of data visualization on comorbidity between mental disorders. This is a webpage that goes along this scientific publication, allowing readers to explore the data themselves.",
        chartDescription: "The webpage includes several chart types, all with buttons allowing to control what part of the dataset is displayed. It is a mix between a data storytelling and a data exploration tool.",
        tools: [{name: "d3.js", link: "https://github.com/holtzy/Como-in-World-Heath-Survey"}],
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 92,
        title: "End of the Covid-19 pandemic",
        date: new Date(2020, 3),
        author: "Mc Kinsey",
        url: "https://www.mckinsey.com/industries/healthcare-systems-and-services/our-insights/when-will-the-covid-19-pandemic-end",
        img: [
            {full: "end-of-covid-pandemic-1.png", zoom: "end-of-covid-pandemic-zoom-1.png", chartId: ["scatter"]},
            {full: "end-of-covid-pandemic-2.png", zoom: "end-of-covid-pandemic-zoom-2.png", chartId: ["line"]},
            {full: "end-of-covid-pandemic-3.png", zoom: "end-of-covid-pandemic-zoom-3.png", chartId: ["heatmap"]},
            {full: "end-of-covid-pandemic-4.png", zoom: "end-of-covid-pandemic-zoom-4.png", chartId: ["barplot"]},
        ],
        contextDescription: "Mc Kinsey regularly post updates on the covid situation, especially concerning future potential trends. Luckily this report is full of nice visuals.",
        chartDescription: "It's great to see such a variety of vizzes in a business report. They are very epurated and all follow the same style guideline which make them worth sharing here.",
        tools: undefined,
        luminosity: [ "light"],
        interactive: false
    },
    {
        id: 93,
        title: "French folks migration",
        date: new Date(2018, 3),
        author: "Etienne Come",
        url: "https://www.comeetie.fr/galerie/wind/",
        img: [
            {full: "french-folks-migration.png", zoom: "french-folks-migration-zoom.png", chartId: ["map", "connection"]},
        ],
        contextDescription: "A migration map showing how french people are moving inside their country. What's really interesting here is that you can select a subset of the population based on sex or work category. Stunning result!",
        chartDescription: "This migration map is very much inspired from the wind map of Tobler et al. that is also feature in dataviz-inspiration.com.<br>Note: the static visual is disappointing but the animated version is mesmerizing!",
        tools: undefined,
        luminosity: [ "light"],
        interactive: true
    },
    {
        id: 94,
        title: "Transphobic hate crimes in Sweden",
        date: new Date(2022, 0),
        author: "Georgios Karamanis",
        url: "https://karaman.is/blog/2022/1/tidytuesday-20221",
        img: [
            {full: "transphobic-crimes-sweden.png", zoom: "transphobic-crimes-sweden-zoom.png", chartId: ["barplot"]},
        ],
        contextDescription: "Reported crimes that the police classified as hate crimes and where killer identified hate as the underlying motive.",
        chartDescription: "A simple yet clean horizontal barplot.",
        tools: [{name: "R", link: "https://github.com/gkaramanis/tidytuesday/tree/master/2022/2022-week_01"}],
        luminosity: [ "light"],
        interactive: false
    }
]
