import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { MasonryItem } from "../components/MasonryItem";
import { vizList } from "../util/viz-list";

const Home: NextPage = () => {
  return (
    <div className="wrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <h1 className="text-xl text-blue-100">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="">
          Get started by editing <code className="">pages/index.tsx</code>
        </p>

        <div style={{ columnCount: 3, width: "100%", columnGap: "1rem" }}>
          {vizList.map((vizItem, i) => {
            return <MasonryItem key={i} vizItem={vizItem} />;
          })}
        </div>
      </main>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
